// <auto-generated />
using System;
using MagicVillaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250628065756_SeedVillaTableWithCreatedDate")]
    partial class SeedVillaTableWithCreatedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVillaApi.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2025, 6, 28, 12, 27, 54, 337, DateTimeKind.Local).AddTicks(4926),
                            Details = "npst nsdf nasdf asd asd asdf asdf",
                            ImageUrl = "test.jpg",
                            Name = "Royal Villa",
                            Occupancy = 5,
                            Rate = 55.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2025, 6, 28, 12, 27, 54, 337, DateTimeKind.Local).AddTicks(4946),
                            Details = "npst nsdf nasdf asd asd asdf asdf",
                            ImageUrl = "test.jpg",
                            Name = "Royal Villa2",
                            Occupancy = 5,
                            Rate = 55.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2025, 6, 28, 12, 27, 54, 337, DateTimeKind.Local).AddTicks(4947),
                            Details = "npst nsdf nasdf asd asd asdf asdf",
                            ImageUrl = "test.jpg",
                            Name = "Royal Villa3",
                            Occupancy = 5,
                            Rate = 55.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreatedDate = new DateTime(2025, 6, 28, 12, 27, 54, 337, DateTimeKind.Local).AddTicks(4949),
                            Details = "npst nsdf nasdf asd asd asdf asdf",
                            ImageUrl = "test.jpg",
                            Name = "Royal Villa4",
                            Occupancy = 5,
                            Rate = 55.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreatedDate = new DateTime(2025, 6, 28, 12, 27, 54, 337, DateTimeKind.Local).AddTicks(4951),
                            Details = "npst nsdf nasdf asd asd asdf asdf",
                            ImageUrl = "test.jpg",
                            Name = "Royal Villa5",
                            Occupancy = 5,
                            Rate = 55.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
